name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-node-modules-
      - name: Install Dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: List .next folder recursively
        run: find .next
      - name: Persist Build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: .next
          retention-days: 1
          if-no-files-found: error

  deploy-frontend-aws:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Restore Build
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: .next